AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  mail-digest-backend

  Backend for the MailDigest application, containing a scheduled task for summaries and a webhook for Telegram.

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

Globals:
  Function:
    Timeout: 30
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
    Tags:
      Project: mail-digest
      ManagedBy: SAM
      Environment: !Ref Environment
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        SUPABASE_URL_SSM_NAME: !Sub "/mail-digest/${Environment}/supabase-url"
        SUPABASE_SERVICE_KEY_SSM_NAME: !Sub "/mail-digest/${Environment}/supabase-service-key"
        OPENAI_API_KEY_SSM_NAME: !Sub "/mail-digest/${Environment}/openai-api-key"
        GOOGLE_CLIENT_ID_SSM_NAME: !Sub "/mail-digest/${Environment}/google-client-id"
        GOOGLE_CLIENT_SECRET_SSM_NAME: !Sub "/mail-digest/${Environment}/google-client-secret"
        TELEGRAM_BOT_TOKEN_SSM_NAME: !Sub "/mail-digest/${Environment}/telegram-bot-token"
        TELEGRAM_WEBHOOK_SECRET_TOKEN: !Sub "/mail-digest/${Environment}/telegram-webhook-secret-token"
        LANGSMITH_TRACING_SSM_NAME: !Sub "/mail-digest/${Environment}/langsmith-tracing"
        LANGSMITH_ENDPOINT_SSM_NAME: !Sub "/mail-digest/${Environment}/langsmith-endpoint"
        LANGSMITH_API_KEY_SSM_NAME: !Sub "/mail-digest/${Environment}/langsmith-api-key"
        LANGSMITH_PROJECT_SSM_NAME: !Sub "/mail-digest/${Environment}/langsmith-project"
  Api:
    TracingEnabled: true

Resources:
  SummaryJobQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "MailDigest-SummaryJobQueue-${Environment}"
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SummaryJobDLQ.Arn
        maxReceiveCount: 3

  SummaryJobDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "MailDigest-SummaryJobDLQ-${Environment}"

  DailySummaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      CodeUri: src/
      Handler: daily_summary_handler.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt SummaryJobQueue.QueueName
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameters
                - ssm:GetParameter
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/mail-digest/${Environment}/*"
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref SummaryJobQueue
          FUNCTION_NAME: "DailySummaryFunction"
      Events:
        DailySummaryTrigger:
          Type: Schedule
          Properties:
            Schedule: "cron(0 23 * * ? *)"
            Name: !Sub "MailDigest-DailyTrigger-${Environment}"
            Description: Aciona o dispatcher de resumos diários

  SummaryWorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      CodeUri: src/
      Handler: summary_worker_handler.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameters
                - ssm:GetParameter
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/mail-digest/${Environment}/*"
      Environment:
        Variables:
          FUNCTION_NAME: "SummaryWorkerFunction"
      Events:
        SummaryJobQueueTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt SummaryJobQueue.Arn
            BatchSize: 1

  TelegramWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: telegram_webhook_handler.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameters
                - ssm:GetParameter
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/mail-digest/${Environment}/*"
      Environment:
        Variables:
          FUNCTION_NAME: "TelegramWebhookFunction"
      Events:
        TelegramWebhook:
          Type: Api
          Properties:
            Path: /telegram-webhook
            Method: post

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"

Outputs:
  TelegramWebhookApi:
    Description: API Gateway endpoint URL for Telegram Webhook function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/telegram-webhook/"
  DailySummaryFunctionArn:
    Description: ARN da função Lambda "Dispatcher" de Resumo Diário
    Value: !GetAtt DailySummaryFunction.Arn
  SummaryWorkerFunctionArn:
    Description: ARN da função Lambda "Worker" de Resumo
    Value: !GetAtt SummaryWorkerFunction.Arn
  SummaryJobQueueUrl:
    Description: URL da fila SQS para os trabalhos de resumo
    Value: !Ref SummaryJobQueue
